---
- name: install apache on ubuntu server
  hosts: appservers
  become: true
  tasks: 
  - name: install apache2
    ansible.builtin.apt:
      name: apache2
      state: present
      update_cache: yes
    notify: start apache2 service

  - name: modify apache config
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: "# handler test"
    notify: restart apache2

  handlers:
  - name: restart apache2
    ansible.builtin.service:
      name: apache2
      state: restarted

