---
- name: Install and start Tomcat on Ubuntu and RHEL
  hosts: all
  become: true

  vars:
    tomcat_version: "9.0.85"

    java_pkg:
      Debian: default-jdk
      RedHat: java

  tasks:
  - name: Install Java
    ansible.builtin.package:
      name: "{{ java_pkg[ansible_os_family] }}"
      state: present

  - name: Download Tomcat from Apache archive
    ansible.builtin.get_url:
      url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
      dest: "/opt/apache-tomcat-{{ tomcat_version }}.tar.gz"
      mode: '0644'

  - name: Extract Tomcat
    ansible.builtin.unarchive:
      src: "/opt/apache-tomcat-{{ tomcat_version }}.tar.gz"
      dest: /opt
      remote_src: yes
      creates: "/opt/apache-tomcat-{{ tomcat_version }}"

  - name: Ensure startup script is executable
    ansible.builtin.file:
      path: "/opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh"
      mode: '0755'

  - name: Start Tomcat
    ansible.builtin.command: "/opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh"
    args:
      chdir: "/opt/apache-tomcat-{{ tomcat_version }}/bin"

